---
title: "Predicting rideshare demand in New York City"
author: "Zhenzhao Xu"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: true
editor_options: 
  markdown: 
    wrap: sentence
  chunk_output_type: inline
---

```{r}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	results=FALSE,
	fig.align="center",
	cache=T
)
```

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(patchwork)
library(ggplot2)
library(viridis)
library(gridExtra)
library(knitr)
library(lubridate)
library(riem)

options(scipen=999)
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
source("functions.r")

p5 = inferno(5)
p2 = p5[c(4,2)]

v = mapview::mapview

# NAD83(2011) / San Francisco CS13
crs = 7131
```


## 1. Introduction

Parking fee?

parking Citations
https://data.sfgov.org/Transportation/SFMTA-Parking-Citations/ab4h-6ztd

Parking time limits (from ? to ? / up to ? hours)
https://data.sfgov.org/Transportation/Parking-regulations-except-non-metered-color-curb-/hi6h-neyh


https://www.way.com/parking//37.7879938/-122.4074374/Union-Square/


```{r}
meter_trans = read.csv("./data/meter_trans_2021-09.csv")
meter_trans%>%nrow()

meters = st_read("./data/meters.geojson")%>%
  select(post_id, ms_space_num, on_offstreet_type, active_meter_flag, meter_type,
         street_id, street_seg_ctrln_id, longitude, latitude, geometry)%>%
  st_transform(crs)%>%
  mutate(
    street_seg_ctrln_id = street_seg_ctrln_id%>%as.numeric()%>%as.character(),
    ms_space_num = as.numeric(ms_space_num),
    ms_space_num = if_else(ms_space_num==0,1,ms_space_num)
  )

meters.bySegId = meters%>%st_drop_geometry()%>%
  group_by(street_seg_ctrln_id)%>%
  summarise(ms_space_num = n())%>%
  # filter(on_offstreet_type=="ON")%>%
  left_join(parking_seg_census,by="street_seg_ctrln_id")

meters.bySegId%>%
  ggplot()+
  geom_point(aes(ms_space_num,PRKG_SPLY))+
  geom_abline(intercept = 0, slope = 1,color="red")
```


Weather

```{r}
weather.SF <- 
  riem_measures(station = "SFO", date_start = "2021-09-01", date_end = "2021-10-01")

weather.Panel <-  
  weather.SF %>%
  mutate_if(is.character, list(~replace(as.character(.), is.na(.), "0"))) %>% 
  replace(is.na(.), 0) %>%
  mutate(interval60 = ymd_h(substr(valid, 1, 13))) %>%
  mutate(week = week(interval60),
         dotw = wday(interval60, label=TRUE)) %>%
  group_by(interval60) %>%
  summarize(Temperature = max(tmpf),
            Percipitation = sum(p01i),
            Wind_Speed = max(sknt)) %>%
  mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))
```

panel

```{r}
study.panel =
  expand.grid(interval60 = unique(weather.Panel$interval60), 
              start.station.id = unique(parking_seg_census$street_seg_ctrln_id)) 
nrow(study.panel)

meter_trans = meter_trans%>%mutate(
  interval60 = floor_date(ymd_hms(session_start_dt), unit = "hour"),
  parking_time = ymd_hms(session_end_dt)-ymd_hms(session_start_dt)
)
meter_trans[1:10000,]%>%view()

```

interval60 = floor_date(ymd_hms(starttime), unit = "hour"),
         interval15 = floor_date(ymd_hms(starttime), unit = "15 mins"),













